export const SEARCH_MOVIES = 'SEARCH_MOVIES';
export const GET_MOVIE = 'GET_MOVIE';
export const ADD_FAVORITE = 'ADD_FAVORITE';
export const GET_FAVORITES = 'GET_FAVORITES';
export const GET_FAVORITE = 'GET_FAVORITE';
export const REMOVE_FAVORITE = 'REMOVE_FAVORITE';
export const CHECK_FAVORITE = 'CHECK_FAVORITE';
